version: "3.7"
services:
  minio:
    image: minio/minio
    container_name: "minio"
    command: "server /data --console-address ':9001'"
    # environment:
    # MINIO_ROOT_USER: minioadmin
    # MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9100:9000"
      - "9101:9001"
    volumes:
      - ./miniodata:/data
